% Inicializa la señal de 4k
FRECUENCIA_MUESTREO  = 4096;       % frec de muestreo
ARCHIVO_MUESTRAS =  'L-L1_LOSC_4_V1-1126259446-32.txt';
SENIAL_ORIGINAL = load (ARCHIVO_MUESTRAS);
LONGITUD_SENIAL = length(SENIAL_ORIGINAL);
FREC_NYQUIST = FRECUENCIA_MUESTREO/2;
FREC_INICIAL_SENIAL = 35;
FREC_FINAL_SENIAL = 350;
TIEMPO_INICIAL_SENIAL= 16;
TIEMPO_FINAL_SENIAL = 17;

UMBRAL_FILTRO_AUTOMATICO = 1e-17;
ORDEN_FILTRO = 500;

%para esectrogramas
ESPECTRO_WINDOW_SIZE = 100;
ESPECTRO_WINDOW = hamming(ESPECTRO_WINDOW_SIZE);
ESPECTRO_OVERLAP = ESPECTRO_WINDOW_SIZE * 0.8;
ESPECTRO_NFFT= 4000;
ESPECTRO_COLORMAP='bone';
%quito la continua
SENIAL_SIN_CONTINUA = SENIAL_ORIGINAL - mean(SENIAL_ORIGINAL);
ESPECTRO_SENIAL_SIN_CONTINUA = fft(SENIAL_SIN_CONTINUA);

